/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Force update: skip waiting and claim clients immediately
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache static assets (images, fonts) with limit — Safari has strict storage quota
registerRoute(
  ({ request }) => request.destination === 'image' || request.destination === 'font',
  new CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// API calls — NEVER cache, always go to network
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkOnly()
);

// Socket.IO — never cache
registerRoute(
  ({ url }) => url.pathname.startsWith('/socket.io/'),
  new NetworkOnly()
);

// Push Notification Handler
self.addEventListener('push', (event) => {
  if (!event.data) return;
  try {
    const data = event.data.json();
    // Payload must NOT include message text (E2EE requirement)
    if (data.type === 'new_message') {
      const options: any = {
        body: 'You have a new secure message.',
        icon: '/pwa-192x192.png',
        badge: '/pwa-192x192.png',
        tag: `chat-${data.chatId}`,
        data: { chatId: data.chatId },
        vibrate: [100, 50, 100],
      };
      event.waitUntil(
        self.registration.showNotification('New Message', options)
      );
    }
  } catch (e) {
    console.error('Push error:', e);
  }
});

// Notification Click Handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const chatId = event.notification.data?.chatId;
  const urlToOpen = chatId ? `/?chatId=${chatId}` : '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return (client as WindowClient).focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Background Sync for Offline Messages
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-messages') {
    // Actual message sending happens in the app when it's open.
    // For E2EE, we wait for the app to be in foreground to access keys.
  }
});
